CC=gcc
INC=include
SRC=src
OBJ=obj

all: geometry

geometry: $(OBJ)/geometry.o $(OBJ)/triangle.o $(OBJ)/circle.o
	$(CC) -o $@ -I$(INC) $^ -lm

$(OBJ)/%.o: $(SRC)/%.c $(INC)/%.h 
	$(CC) -c -I$(INC) $< -o $@

$(OBJ)/geometry.o: $(SRC)/geometry.c $(INC)/circle.h $(INC)/triangle.h
	echo "Using Explicit Target"
	$(CC) -c -I$(INC) $< -o $@

